<?php
/**
 * Created by PhpStorm.
 * User: TEM
 * Date: 2019/4/19
 * Time: 15:44
 */

namespace app\controller;


use fast_php\base\Controller;

class Base extends Controller
{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
       session_start();
        //未登录跳转回登陆页面；
//        print_r($user_name. '11');die;
        if (!isset($_SESSION['user_id'])) {
        header("Location: http://local.domain.cn/Login/login?second=1");
        }else{
            return true;
        }

    }
}